### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [1]:
import numpy as np

In [7]:
a = ['강아지', '원숭이', '꽃', '45', '100']
arr = np.array(a)

In [10]:
print(arr, arr.ndim, type(arr))

['강아지' '원숭이' '꽃' '45' '100'] 1 <class 'numpy.ndarray'>


In [54]:
# A1.
a = np.array(['강아지', '원숭이', '꽃', '45', '100'])
a, a.ndim, a.size, type(a), a.dtype, a.shape

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3'),
 1,
 5,
 numpy.ndarray,
 dtype('<U3'),
 (5,))

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
print(np.ones((2,3)))  # ones는 값을 유지하기 위해 사용

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
# A2.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [16]:
arr = np.arange(51, 81)
print(arr, len(arr), arr.size)

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80] 30 30


In [19]:
arr = arr.reshape(6,5)
arr, arr.ndim, arr.shape

(array([[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75],
        [76, 77, 78, 79, 80]]),
 2,
 (6, 5))

In [57]:
# A3.
arr = np.arange(51,81).reshape(6,5)
# np.arange(51,81).reshape(-1,5)
print(arr)

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]
 [76 77 78 79 80]]


#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [26]:
arr = np.arange(51, 81, dtype=float).reshape(6,5)
arr

array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])

In [58]:
# A4.
arr = arr.astype(float)
arr.dtype

dtype('float64')

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [27]:
a = np.array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])

In [28]:
a = a.flatten()
print(a)

[ 1  4  5  6 56 23 45 67  8  4  6 10]


In [30]:
a[5:-1]

array([23, 45, 67,  8,  4,  6])

In [60]:
# A5.

arr2d = np.array([[ 1,  4,  5,  6], [56, 23, 45, 67], [ 8,  4,  6, 10]])
print(arr2d.flatten()[5:11])
print(arr2d.flatten()[5:-1])

[23 45 67  8  4  6]
[23 45 67  8  4  6]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [3]:
a = [1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
arr = np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[7:]=0
arr[0]=10
arr

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

In [61]:
# A6.

arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[0] = 10
arr[7:] = 0
arr

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [9]:
np.random.randint(10, 100, (5,5))

array([[17, 56, 77, 74, 99],
       [12, 36, 37, 70, 46],
       [85, 59, 20, 23, 98],
       [95, 16, 69, 78, 59],
       [70, 86, 88, 13, 95]])

In [62]:
# A7.

np.random.randint(10,99,25).reshape(5,5)
np.random.randint(10,99,(5,5))

array([[57, 69, 83, 55, 31],
       [13, 63, 67, 14, 52],
       [36, 35, 27, 52, 83],
       [73, 75, 98, 19, 72],
       [81, 46, 34, 17, 52]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [14]:
a = np.random.randint(1, 101, 7)
print(a)
print('max =', np.max(a))
print('min =', np.min(a))

[68 65 78 19 69 36 24]
max = 78
min = 19


In [63]:
# A8.

num = np.random.randint(1,100,7)
num, np.max(num), np.min(num)

(array([75,  8, 96, 28, 64, 29, 10]), 96, 8)

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [19]:
a = [[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


b = [[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


c = [[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]

arr_a = np.array(a)
arr_b = np.array(b)
arr_c = np.array(c)

arr_a, arr_b, arr_c

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

In [21]:
np.hstack((arr_a, arr_b, arr_c))  # 가로합치기

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [22]:
np.vstack((arr_a,arr_b, arr_c))  # 세로합치기

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [64]:
# A9.

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
c = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])

# result 1
result2 = np.hstack((a, b, c))

# result 2
result1 = np.vstack((a, b, c))

result1, result2

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]),
 array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
        [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
        [ 7,  8,  9, 17, 18, 19, 27, 28, 29]]))

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [26]:
arr = np.random.choice(100, 40, replace=False)
arr[arr > 50]

array([54, 88, 99, 73, 91, 67, 75, 58, 69, 96, 90, 51, 60, 68, 64, 82, 92,
       89, 66, 61])

In [65]:
# A10.

# 중복없이, 10까지 숫자 중 40개를 추출 가능, randint는 중복생김
n = np.random.choice(100, 40, replace=False)

# 50 보다 큰 숫자만 필터링
n, n[np.where(n>50)], n[n>50]

(array([51, 43, 32, 55, 82,  0, 87,  9, 16, 52, 76, 22,  2, 50, 92, 58, 97,
        88, 26, 12, 18, 48, 90, 31, 34, 72, 81, 77, 23, 89, 17,  1, 27, 98,
        63, 57, 38, 96, 66, 20]),
 array([51, 55, 82, 87, 52, 76, 92, 58, 97, 88, 90, 72, 81, 77, 89, 98, 63,
        57, 96, 66]),
 array([51, 55, 82, 87, 52, 76, 92, 58, 97, 88, 90, 72, 81, 77, 89, 98, 63,
        57, 96, 66]))

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [27]:
kor = np.array( [60,55,70,30,20,90])

In [28]:
np.max(kor)

90

In [29]:
kor[kor>=80]

array([90])

In [32]:
kor[(50<=kor) & (kor<=80)]

array([60, 55, 70])

In [33]:
np.mean(kor)

54.166666666666664

In [66]:
# A11-4.
np.average(kor), round(kor.mean(),3)

(54.166666666666664, 54.167)

In [34]:
np.sum(kor)

325

In [41]:
np.delete(kor, kor<=40, axis=0) # 1차원이니까 axis=0

array([60, 55, 70, 90])

In [67]:
# A11-6.

import copy
kor1 = kor.copy()
num = kor[kor<=40]
kor1, num, np.delete(kor1, np.where(kor<=40))

(array([60, 55, 70, 30, 20, 90]), array([30, 20]), array([60, 55, 70, 90]))

In [42]:
# 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
# 이거 못풀겠네...;;;;
up = kor[kor>=50]
print(

array([60, 55, 70, 90])

In [50]:
# A11-7.

np.where(kor>-50, kor*1.1, kor)

array([66. , 60.5, 77. , 33. , 22. , 99. ])

In [51]:
np.sort(kor)[::-1][0:3]

array([90, 70, 60])

In [70]:
# A11-8.
# 인덱스값으로 실제값 출력

np.sort(kor)[::-1][:3], kor[np.argsort(kor)[::-1][:3]] 

(array([90, 70, 60]), array([90, 70, 60]))

In [52]:
#국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시오

print('합격자 점수:' , kor[kor>=70])
print('불합격자 점수:', kor[kor<70])

합격자 점수: [70 90]
불합격자 점수: [60 55 30 20]


In [71]:
# A11-9.
kor, np.where(kor>=70, "합격", "불합격")

(array([60, 55, 70, 30, 20, 90]),
 array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3'))