# NumPy

In [1]:
# 주피터노트북 셀 스타일 조절
from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고메시지 숨기기
# import warnings\

# warnings.filterwarnings(action='ignore')

C:\Users\Jiyoung\AppData\Local\Temp\ipykernel_19240\2458149073.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


## Numpy 개요
- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 배열이나 행렬 계산에 용이한 메서드를 제공
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함

- 관련 사이트 : http://www.numpy.org
- 일반 List에 비해 빠르고, 메모리 효율적

- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함
R- eference Site
- cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- 데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS

In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
# 메소드와 속성
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

## 넘파이 배열 이해하기

### ndim(dimention, rank)
- 몇 차원인지 반환

In [5]:
a = np.array(0)

In [6]:
a, a.ndim, type(a)  # ( 'array'라는 자료구조, 차원, 타입 )

(array(0), 0, numpy.ndarray)

In [7]:
a = np.array([2, 4, 6])

In [8]:
a, a.ndim, type(a)   # 1차원

(array([2, 4, 6]), 1, numpy.ndarray)

In [9]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)  # 2차원 앞에 '['가 몇개인지 봐도 됨

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [10]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)    # 3차원 = depth가 생기면서 ...

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

### shape
- 행렬의 차원으로, 몇행 몇열인지 반환 = 자료배열 형태 파악

In [12]:
a.shape  # (뎁스, 행, 열) = 2행 3열인데 뎁스가 2개야

(2, 2, 3)

In [13]:
a = np.array(3)
a, a.shape # 행렬아님 = 행렬이 아니라 요소가 하나뿐이라서

(array(3), ())

In [14]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape  # 이건 1차원 = 벡터

(array([1, 3, 5, 7, 9]), (5,))

In [15]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape   # 2차원

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [16]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열  # 3차원

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

### size
- 요소의 수

In [18]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [19]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

## 넘파이 배열
- 리스트를 넘파이 배열로 생성 np.array(리스트)
- 관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple
- 넘파이 구조 배열 시각화 = https://array-3d-viz.vercel.app/

In [21]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [25]:
myArr = np.array(myList)  
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [23]:
myArr

array([10, 56, 77, 23, 44])

In [26]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [27]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3) 구조타입 = <class 'tuple'>, size = 9


In [28]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [30]:
# 길이가 달라(=행렬이 아님) 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
- 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
- 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
- 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [31]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [32]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [33]:
# 넘파이의 산술연산 = 요소별 연산(행렬) = '브로드캐스팅' 한다
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [34]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


### dtype
- https://numpy.org/doc/stable/reference/arrays.dtypes.html
- 데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장함
- (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
- 예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다
- 숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.
- '리스트'도 그냥 객체(o)라고 표현한다

In [3]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [4]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환(문자열과 다른 속성이 섞여있는 것은 오류발생)
print(myArr_c, type(myArr_c), myArr_c.dtype)
# U : 유니코드 문자열

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [5]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


### Inf와 NaN
- 넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
- 다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
- 0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [6]:
# 요소별 연산
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
# nan : 숫자가 안된다

C:\Users\Jiyoung\AppData\Local\Temp\ipykernel_19240\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Jiyoung\AppData\Local\Temp\ipykernel_19240\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [12]:
np.log(0)

C:\Users\Jiyoung\AppData\Local\Temp\ipykernel_19240\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [11]:
np.exp(-np.inf)  # 로그를 지수화

0.0

## 기술통계

In [13]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [14]:
np.mean(x)  # 평균 

4.8076923076923075

In [15]:
np.var(x)  # 분산

115.23224852071006

In [16]:
np.std(x)  # 표준 편차

10.734628476137871

In [17]:
np.max(x)  # 최댓값

23

In [18]:
np.min(x)  # 최소값

-24

In [19]:
np.median(x)  # 중앙값

5.0

### 사분위수
- 사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
- 각각 1사분위수, 2사분위수, 3사분위수라고 한다.
- 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.
- 3Q-1Q = IQR (가장 많이 몰려있는 구간)

- 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [20]:
np.percentile(x, 0)  # 최소값

-24.0

In [21]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [23]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [24]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [26]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기
- np.ones(n) , np.ones((x, y))
- np.zeros(n) , np.zeros((x, y))
- np.empty(n) , np.empty((x, y))
- np.aranges(start, end step)

- reshape(x, y) # 차원 확대
- flatten(x, y) # 차원 축소

In [28]:
# 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 
# 1, 1, 1, 1, 1, 1,  => 값을 유지해주기 위해서 (ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [29]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [31]:
np.ones?

In [30]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [35]:
print(np.zeros(10), np.zeros(10).dtype)  
# 불필요한 값을 날려버리기 위해 또는 무의미한 공간을 채울 때 '패딩' (zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [33]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [38]:
# 메모리가 비어있음 (empty) -> 메모리가 초기화 시키지 않음
# zeros는 메모리 차지하고 있음
# empty인 경우 원래 할당되어 있는 메모리에 있는 값 출력 (메모리를 아끼기 위해)

print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력(어떤 값이 출력될지는 알 수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[         0          1          0]
 [   5570652       1744          0]
 [       768      40312 1031767088]]


In [39]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [40]:
# 1~20으로 구성된 4행 5열의 넘파이 배열
# print(np.array(list(range(1,21))), type(list(range(1,21))))

print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [42]:
# 0~49까지 구성된 넘파이 배열

arr = np.arange(50)
print(arr, len(arr), arr.size)  # 1차원이라서 길이 = 요소의 수f

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [43]:
# linspace 명령이나 logspace 명령은 선형 구간 
# 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.

np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [45]:
# logspace도 동일한 형태로 사용 가능
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
- reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
- 현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [46]:
arr, arr.ndim, arr.shape  # 50개의 값이 들어있는 1차원 행렬

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [48]:
arr = arr.reshape(10,5)  # 10행 5열로 차원을 변환~
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [49]:
arr2 = arr.reshape(5,10)  # 5행 10열로 차원을 변환
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [52]:
# 5행 10열을 계산이 용이하도록 1차원으로 변환하고 싶어!
# 2차원 -> 1차원
# 넘파이배열.flatten()
# lambda로 전처리 해주고 reshape 해주면 끝!

arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim # 다시 평평해졌다!

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [53]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [62]:
print(np.arange(2,101,2).reshape(5,10))

# 5행 = 데이터의 길이, 10열 = col 10개

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [63]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.

arr4 = np.arange(1, 31).reshape(-1, 1) 
# 행과 열 중 하나의 값만 알면, 나머지 칸에 -1을 입력하면 된다
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [64]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [68]:
np.arange(1,21).reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 4)
# rehsape -1은, 행과 무관하게 n개의 컬럼을 만든다

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [74]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [75]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [89]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [90]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [91]:
a.shape = -1, 2
a, a.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 (6, 2))

In [92]:
a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [77]:
# flatten
a.shape = -1   # 값을 -1 하나만 넣으면 flatten이 된다
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [70]:
# 사이즈가 맞아야 한다.
# np.arange(1, 21).reshape(-1, 7)

## 넘파이배열의 자료형 형변환
- 배열명2 = 배열명1.astype(자료형)
- 자료형 = np.float64, np.int32

In [76]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [78]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [79]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [80]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

In [81]:
# 정수형 => 문자열 
# 외울 필요는 없다

matrix.astype('<U5') # str이라고 표시하지 않는다

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [82]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [83]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [84]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [85]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [86]:
# 문자열에 들어간 값 자체가 실수이므로 당연히 불가함
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가 
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [88]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문(실수가 정수보다 더 크니까)

array([3, 5, 7])

## 넘파이 배열의 인덱싱
- 넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열
    
### 1D array

In [93]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [94]:
a[0]

1

In [95]:
a[2]

5

In [96]:
a[-1]

9

In [97]:
a[-5]

1

In [98]:
a[[0, 2, 4]]

array([1, 5, 9])

In [99]:
a

array([1, 3, 5, 7, 9])

In [101]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array([[1,3], [4,2]]) # 일단 행렬부터 만들자
b # 2차원 행렬 완성

array([[1, 3],
       [4, 2]])

In [102]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [104]:
# 인덱싱으로 값 수정도 가능
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [105]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [106]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

### 2D array

In [107]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [108]:
# 2차원 인덱싱할 때, 값을 하나만 넣으면 '행 인덱싱'
a[0]

array([0, 1, 2, 3, 4])

In [109]:
a[1]

array([5, 6, 7, 8, 9])

In [110]:
a[-1]

array([10, 11, 12, 13, 14])

In [111]:
a[-2]

array([5, 6, 7, 8, 9])

In [112]:
a[-3]

array([0, 1, 2, 3, 4])

In [116]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [113]:
# 이제 차원 인덱싱~
# 값이 2개 들어가면 '행/열 인덱싱'
a[0, 0]

0

In [114]:
a[0, 1]

1

In [117]:
a[1, 0]

5

In [118]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [119]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [121]:
# 마지막행 값을 모두 10으로 바꿔보자
# 값은 하나만 넣어도, 길이에 맞춰서 모두 넣어도 결과는 동일

a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [122]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [124]:
matrix_a = np.arange(10)  # 1차원
matrix_b = np.arange(12).reshape(3,4)  # 2차원

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [125]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [126]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

0

In [129]:
# 추출에서 또 추출할 수 있음 = 이렇게 되면 1차원이 된 것
# (차원을 쪼개서 다운그레이드)

matrix_b[0][0]

0

In [130]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

In [132]:
# 위와 같은 동작
matrix_b[-1][-1]

11

In [133]:
# matrix_b에서 3번째행 1번째열의값을 100으로 변경해보자
matrix_b[2,0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

## 넘파이배열 슬라이싱
- 1차원
- 넘파이배열[:end]
- 넘파이배열[start:]
- 넘파이배열[start:end]
- 넘파이배열[start:end:step]
- 2차원
- 넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

### 1D array

In [134]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [135]:
a[:]

array([1, 3, 5, 7, 9])

In [136]:
 a[1:]

array([3, 5, 7, 9])

In [137]:
a[-1:]

array([9])

In [138]:
a[:3]

array([1, 3, 5])

In [139]:
a[:-1]

array([1, 3, 5, 7])

In [140]:
a[1:4]

array([3, 5, 7])

In [141]:
a[1:-1]

array([3, 5, 7])

In [142]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
a[::2]

array([0, 2, 4, 6, 8])

In [144]:
a[::5]

array([0, 5])

In [146]:
a[::-1]  # 이건 역순으로 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [147]:
# 홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [148]:
a[:-2:2]

array([0, 2, 4, 6])

### 2D array

In [3]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [4]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
a[3:]

array([], shape=(0, 5), dtype=int32)

In [7]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [8]:
a[-3:] # 결국 앞에서부터 다 뽑으라는 뜻

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
a[:0] # 0인덱스에서 -1을 하면 없는 값

array([], shape=(0, 5), dtype=int32)

In [10]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

- 2차원 슬라이싱

In [11]:
a[:, :]  # 행의 범위, 열의범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [13]:
a[:, 3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [14]:
a[:, -1:]

array([[14],
       [19],
       [24]])

In [15]:
a[:, -4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [16]:
a[:, :1]

array([[10],
       [15],
       [20]])

In [166]:
a[:, :5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [167]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
a[:, :-1]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [169]:
a[:, 0:1]  # 0번 인덱스만 나옴

array([[10],
       [15],
       [20]])

In [170]:
a[:, 2:3] # 2번 인덱스만 나옴

array([[12],
       [17],
       [22]])

In [171]:
a[:, 1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [17]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [19]:
a[:, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [20]:
a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [21]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [22]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
a[::-1, ::-1]  # 행, 열 다 뒤집어짐

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [25]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

In [26]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [27]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [28]:
# 1번째열만 출력
matrix_c[:, 0]

array([ 1,  6, 11, 16, 21])

In [29]:
# 3,4 번째열만 출력
matrix_c[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [30]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [31]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [32]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [33]:
# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


## 전치행렬
- 넘파이배열.T(트랜스포즈) : 행과 열 구조 변경
- 행이 열로 , 열이 행으로
- 트랜스포즈는 대문자 T 사용
- reshape은 일단 처음부터 끝까지 나열(flatten)하고 난 뒤에 차원으로 바꿔줌

In [180]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [181]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [182]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 
- np.random.randint(start, end, n) : 정수 난수
- np.random.randint(start, end, (i, j))

In [ ]:
np.random?

In [183]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([8, 9, 8, 8, 5, 3, 5, 6, 7, 7])

In [184]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[5, 6, 3, 7, 7],
       [4, 3, 1, 6, 1]])

### 섞기
- np.random.shuffle(넘파이배열) 원본에 바로 적용

In [185]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [186]:
np.random.shuffle(matrix_e)
matrix_e

array([ 2,  4,  3,  6,  7,  1,  5, 10,  9,  8])

---

- Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [187]:
matrix_b = np.arange(1,46)
matrix_b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [188]:
np.random.shuffle(matrix_b)
matrix_b

array([36, 17, 15, 13,  3, 37, 29, 22, 25, 16, 18,  5, 45, 24, 14, 19, 40,
       35, 31, 28, 12, 26, 39, 38, 20,  4, 27,  2, 23, 41,  8,  6, 43, 42,
       32, 44,  9, 34, 33,  7, 11, 30, 21,  1, 10])

In [189]:
matrix_b[:6]

array([36, 17, 15, 13,  3, 37])

- 강사님 답안

In [ ]:
num= np.arange(1,47)
np.random.shuffle(num)
num[:6]

In [ ]:
np.random.randint(1,47,6)

---

### 실수 난수
- np.random.randn(n) np.random.randn(i, j)
- 정규화  randn

In [191]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-0.72056676,  0.98122365,  0.80976311, -0.05395908, -0.46398379,
        1.54400893,  0.8094545 , -1.83890429, -0.43897289,  0.14309655])

In [192]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.04132786,  0.01030865, -0.413789  , -0.73869518],
       [ 1.05796587,  0.45438585, -0.80714128, -2.2504942 ],
       [-0.66569142, -0.17397264, -0.8979538 , -0.00609874],
       [-1.60970471,  1.04690025,  0.71742947,  0.74137473]])

In [193]:
matrix1.max(), matrix1.min()

(1.5440089332471612, -1.8389042860757268)

### 집계함수에서의 축
- 2차원에서의 집계합수(sum, mean)
- axis = 0, 1
- np.sum(넘파이배열, axis=0/1)
- np.mean(넘파이배열, axis=0/1)
- np.sort(넘파이배열, axis=0/1)

In [195]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[44,  5, 28, 30, 45],
       [15, 23, 37, 22, 37],
       [37, 22,  9, 40, 34],
       [36, 17, 12, 48, 43],
       [17, 45, 28, 18, 33]])

In [198]:
np.sum(m1, axis=0) # (x)행 합계 
# 어떤 방향으로 무엇을 계산할 건데?에 대한 표시

array([149, 112, 114, 158, 192])

In [200]:
np.sum(m1, axis=1) # 열(y) 합계

array([152, 134, 142, 156, 141])

In [201]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

152

- np.sort()
- axis를 기본으로 한 정렬
- 즉, axis 방향으로 요소별로 sort 하는 것 (행렬이 바뀐 것이 아니라)

In [202]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[27, 48, 24],
       [14, 40, 17],
       [41, 18, 29],
       [41, 33, 49]])

In [203]:
np.sort?

In [205]:
np.sort(m2)  # 행 안에서 열 정렬

array([[24, 27, 48],
       [14, 17, 40],
       [18, 29, 41],
       [33, 41, 49]])

In [204]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[14, 18, 17],
       [27, 33, 24],
       [41, 40, 29],
       [41, 48, 49]])

In [206]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[41, 33, 49],
       [41, 18, 29],
       [14, 40, 17],
       [27, 48, 24]])

In [208]:
np.sort(m2, axis=1) # 열방향 오름차순
# 제일 작은 수들이 맨 앞으로 이동

array([[24, 27, 48],
       [14, 17, 40],
       [18, 29, 41],
       [33, 41, 49]])

- 인덱스 소팅
- np.argsort(넘파이배열, axis=0,1)
- 정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [210]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [211]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
- 삽입
  - np.insert(배열, 위치인덱스, 값, axis=0/1)
  - 2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
- 삭제
    - np.delete(배열명, 위치인덱스, axis=0/1)

In [2]:
import numpy as np

In [3]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [5]:
m3[-1]

10

In [6]:
np.insert?

In [7]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식
# -1 인덱싱 위치가 맨끝이 아님(뒤에서 두번째) = 위치 참고할 것

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [8]:
np.insert(m3, len(m3), 500)  # 맨 뒤에 인덱싱 하려면 len() 이용할 것

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [9]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입
# 차원을 모르면 1차원이 디폴트..

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [11]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [12]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [13]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [14]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [15]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [16]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
- np.vstack((배열1,배열2....)) : 세로 합치기
- np.hstack((배열1,배열2....)) : 가로 합치기
- np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [20]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [21]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [22]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [23]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask
- 조건절의 결과는 True, False로 반환
- True인 결과의 데이터 반환
- 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [24]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
matrix > 10  # 조건문 필요 없이 바로~

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [26]:
matrix[matrix > 10] # 인덱싱으로 넣으면 이렇게~

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
(matrix > 10).sum() # 길이를 추출할 때 len() 필요X -> True가 1이니까 합계 구하면 끝

10

Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크고 70보다 작은 수를 출력하라

In [32]:
# 내가 한 거
num = np.random.randint(1,100,30)
print(num)

(num > 30) & (num < 70)

[52 84 99 59 35 50 50 40 97 33  5  7 90 92 52 68 10 63 33 59 40 44 12  3
 55 26 84 25 96 71]


array([ True, False, False,  True,  True,  True,  True,  True, False,
        True, False, False, False, False,  True,  True, False,  True,
        True,  True,  True,  True, False, False,  True, False, False,
       False, False, False])

In [33]:
num[(num > 30) & (num < 70)]

array([52, 59, 35, 50, 50, 40, 33, 52, 68, 63, 33, 59, 40, 44, 55])

In [34]:
# 답안
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([37, 90, 42, 92, 20, 75,  4, 67, 92, 63, 25, 74, 54, 64, 85, 31, 86,
        68, 30, 60, 44, 14, 98, 28,  9, 16, 54, 24, 48, 99]),
 array([37, 42, 67, 63, 54, 64, 31, 68, 60, 44, 54, 48]))

In [35]:
# ~ 은 reverse를 의미  # & 조건 앞에 ~ 쓰면  not의 의미
num[~(num > 30) & (num < 70)]

array([20,  4, 25, 30, 14, 28,  9, 16, 24])

In [36]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([92,  4, 92, 98,  9, 99])

In [37]:
num[~(num < 10) | (num > 90)]

array([37, 90, 42, 92, 20, 75, 67, 92, 63, 25, 74, 54, 64, 85, 31, 86, 68,
       30, 60, 44, 14, 98, 28, 16, 54, 24, 48, 99])

## fancy indexing(filtering)
- 넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

    - 넘파이배열1[넘파이배열2]
    - 넘파이배열2 : 인덱스 역할 (only 정수형)

In [38]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([43, 77,  7, 46, 92, 94,  8, 42, 58, 57, 20, 95, 61, 51, 95, 36, 95,
        39, 62, 69, 58, 15, 39, 23, 78, 44, 63, 86, 91, 74]),
 array([43,  7, 46, 20, 58]))

## np.where()를 이용한 필터링
- 정말 많이 씀!!!
- np.where(조건식) : 조건식 만족하는 인덱스 반환
- np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
- 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [39]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를(=원본을 반환하라), 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [40]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))

In [ ]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

In [ ]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

## 멘토님 추가 코드

In [1]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
              4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print('갯수 :',len(x))
print('합계 :',np.sum(x))
print('평균 :',np.mean(x), np.average(x))
print('분산 :',np.var(x))
print('표준편차 :',np.std(x))
print('최대 :',np.max(x))
print('최소 :',np.min(x))
print('중앙값 :',np.median(x))

갯수 : 26
합계 : 125
평균 : 4.8076923076923075 4.8076923076923075
분산 : 115.23224852071006
표준편차 : 10.734628476137871
최대 : 23
최소 : -24
중앙값 : 5.0


In [5]:
import numpy as np
ar = np.arange(10).reshape(2,5)
print(ar)
print(ar.T) # 행과 열을 변경

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [6]:
print(ar.transpose()) # 행과 열을 변경

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [7]:
# 0 19 4행 5열 -> 행과 열을 교환
br = np.arange(20).reshape(4, 5)
print(br)
print(br.T)
print(br.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
